--1
SELECT * FROM CITY
WHERE COUNTRYCODE = 'USA' AND POPULATION > 100000;
--2
SELECT NAME FROM CITY
WHERE COUNTRYCODE = 'USA' AND POPULATION > 120000;
--3
SELECT * FROM CITY;
--4
SELECT * FROM CITY
WHERE ID = 1661;
--5
SELECT * FROM CITY
WHERE COUNTRYCODE = 'JPN';
--6
SELECT NAME FROM CITY
WHERE COUNTRYCODE = 'JPN';
--7
SELECT CITY, STATE FROM STATION;
--8
SELECT DISTINCT CITY
FROM STATION
WHERE MOD(ID, 2) = 0
ORDER BY CITY;
--9
SELECT COUNT(CITY) - COUNT(DISTINCT CITY)
FROM STATION;

